language: python

python: "3.6"

jobs:
  include:
    - stage: "test"
      name: "unit tests"
      before_install:
        - sudo apt-get install -y -q mpich libmpich-dev
      install:
        - pip install pytest pytest-cov pytest-mock
        - pip install coveralls
        - pip install -r requirements.txt
        - ./.build_bingocpp.sh
      before_script:
        - export PYTHONPATH=$PYTHONPATH:$PWD
      script:
        - python -c "import bingo"
        - tests/run_tests.sh
      after_script:
        - coveralls

  - install:
      - pip install -r requirements.txt
      - ./.build_bingocpp.sh
    before_script:
      - export PYTHONPATH=$PYTHONPATH:$PWD
    script:
      - python tests/performance_benchmarks.py
      - python tests/island_benchmarks.p
    name: "performance benchmarks"


  - install:
      - pip install -r requirements.txt
      - pip install nbconvert
    before_script:
      - export PYTHONPATH=$PYTHONPATH:$PWD
    script:
      - examples/.test_examples.sh
    name: "examples"